name: {{cookiecutter.package_name}}
channels:
 - conda-forge
{%- if cookiecutter.use_snakemake == "yes" %}
 - bioconda
{%- endif %}
 - defaults
dependencies:
 - python={{cookiecutter.python_version}}
 - jupyter
 - scipy
 - numpy
 - pandas
 - scikit-learn
 - matplotlib
 - bokeh
 - colorcet
{%- if cookiecutter.use_snakemake == "yes" %}
 - snakemake
{%- endif %}
 - pip
