name: {{cookiecutter.package_name}}
channels:
 - conda-forge
 - defaults
dependencies:
 - python={{cookiecutter.python_version}}
 - jupyter
 - scipy
 - numpy
 - pandas
 - scikit-learn
 - numpy
 - matplotlib
 - bokeh
 - colorcet
 - pip